version: '3'

#networks:
# default:
#  driver: bridge

services:

  db:
    image: mongo:3.7.9
    restart: always
    container_name: db_app
    ports:
      - '27017:27017'
    environment:
     - MONGO_INITDB_DATABASE=documents
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin_password

    expose:
      - 27017

#    networks:
#     default:



  redis:
    image: redis:7
    container_name: redis_app
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    ports:
      - '6379:6379'
#    command: --port 6379
##    expose:
##      - 6379

#    networks:
#      default:

#  tesseract:
#    build: .
#    container_name: tesseract_app
#    networks:
#     default:

  app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8007:8000
    depends_on:
      - db
      - redis
#    networks:
#      default:
#

  celery:
    build:
      context: .
    container_name: celery_app

#    env_file:
#      - .env
    command:  celery -A tasks:app worker --loglevel=INFO
    depends_on:
      - redis
#        condition: service_healthy
##      links:
##        - redis
#
#    networks:
#      default:
#



